### ISSUE TITLE
CPU bars do not refect niced load

### ISSUE THREAD

**Issue by wezm** [epilys/bb#10]
The build script we use at my work runs the compiler with `nice 10`. When there is nothing much going on this still represents a full load on the machine but this is not reflected in the CPU bar graphs.

In the following screenshot note that the load average is 10, and the CPU load is 93% but the bars are mostly empty.

![Screenshot from 2019-11-04 10-18-51](https://user-images.githubusercontent.com/21787/68093722-c86f8700-feec-11e9-9c41-0d8b23ff05a2.png)

I note that under the same circumstances `top` fills the bars:

![Screenshot from 2019-11-04 10-23-52](https://user-images.githubusercontent.com/21787/68093775-39af3a00-feed-11e9-8fda-a65cc43af3be.png)

**Comment by epilys** [comment]
Good catch: the problem is [here](https://github.com/epilys/bb/blob/master/src/ui/components/kernel.rs#L160), where only user/system/iowait time is reckoned. The rest of the time values are in the [`Stat` struct](https://github.com/epilys/bb/blob/master/src/ui/components/utilities.rs#L71) so it should be straight-forward to fix.
